### PR TITLE
lmm loops

### PR DESCRIPTION
**Pull request by masinter**
- remove or move to obsolete loops files from src
- Gauges Rules and Truckin cleanup. Still need to compile TRUCKIN
- fix record access OBJECT, recompile TRUCKIN
- compile players
- wrong directory for playes, fixed
- move sources to same directory as loops .DFASLs since file package works better
- compile rules file, remaking files
- Start expanding readme to explain what's where
- pushing through compiling and removing duplicates
- more hacking on compiling
- WIP: Still working on compiling trukin and getting it to run

### CODE REVIEW

**Comment by nbriggs** [comment]
Please try doing `(LOAD "LOADLOOPS")` then `(LOADLOOPS NIL 'SOURCE)` in a clean image before declaring this to be progress...

**Comment by masinter** [comment]
Actually, I think this version is better than 'main', but perhaps that's not clear.
The Loops loader had code that is obsolete -- loading floppies and finding fonts.
The separation of source code from compiled doesn't seem worth the bother to maintain.
There were duplicate files and deprecated ones that are moved to `obsolete`.
The DFASL files had been compiled for Medley 2.0 which is obsolete.

Current state is that CL:COMPILEFILE(TRUCKIN) complains when it tries to compile a function with (⬅️ Super new) that isn't inside a Method implementation and the macro expander for ⬅️Super doesn't see a binding for *SelectorOfMethodBeingCompiled* when compiling GameClass.New.  I can make a TRUCKIN.DFASL by skipping 4-5 of the errors by RETFROM(COMPILER::COMPLE-AND-DUMP) when it gets that error.
The alternative is to run TRUCKIN interpreted by LOAD(TRUCKIN) instead of or before LOAD(TRUCKIN.DFASL) (or `LoadTruckin()`.

The initialization `(⬅️ ($ Truckin) New)` seems to work, but `(⬅️ PlayerInterface BeginGame)` gives winds up selecting players but they have a name of NIL.

Probably a better attack would be to try to dig out the 1.1 test suite and try to debug this in smaller pieces. 

This seems to make use of CL:COMPILER-LET in a way that is hard to reason about....
Interlisp uses caching of macro expansions that was causing other errors, and I added some advice in LOADLOOPS to disable that when doing CL:COMPILE-FILE (since the caching won't be useful because the macro s-expression is read in new).

**Comment by nbriggs** [comment]
I didn't see any floppy or font related stuff in LOADLOOPS.   Also, it's pretty much impossible to load with the code that complains every time a `\xxx` function is defined (even when it's the initial definition, not a redefinition).

**Comment by masinter** [comment]
Putting this back to "draft".  I think I found out some interesting questions about LOOPs status but not ncessarily the right answers.

**Comment by masinter** [comment]
The README.md has the status and instructions on how to load.

**Comment by nbriggs** [comment]
Still can't load sources --  

Screen Shot 2022-08-13 at 8 24 19 PM

**Comment by masinter** [comment]
Sorry I was confused -- I tried loading LOADLOOPS and calling (LOADLOOPS NIL 'SOURCE) in a clean LISP.SYSOUT without my Greet loaded and got the same error. There was something in the prompt window 
image
about LispWindowAV not installed.  I'm trying to track down why it's caused.
I made a branch called "before" and I'm running in "git checkout before" .

**Comment by masinter** [comment]
> Sorry I was confused -- I tried loading LOADLOOPS and calling (LOADLOOPS NIL 'SOURCE) in a clean LISP.SYSOUT without my Greet loaded and got the same error. There was something in the prompt window image about LispWindowAV not installed. I'm trying to track down why it's caused. I made a branch called "before" and I'm running in "git checkout before" .

Will open a new issue to run this down

**Pull request merged**
