### PR TITLE
clean retranscript of AVTests

### PR DESCRIPTION
**Pull request by masinter**
replaces PR #17 to only include the @skaisler1 test handler

### CODE REVIEW

**Comment by skaisler1** [comment]
Larry:
 
Thanks very much for helping!
I would never have detected this.
 
so, questions:
1. Should the distribution of Medley now include the New Interlisp Readtable as default?
I would suggest it should. I had not seen a notice of this.
 
2. Did you make a change to the  LOOPS Source code, so that I should download a new version?
 
3.We need to com up with a mechanism for alerting users about such changes as they occur. I am sure that every release of Medley and, eventually, of LOOPS and other code, that changes will be made and they need to be posted somewhere for people to read.
 
We should not require them, I don't think, to go to GitHub to find out what is changing.
 
Steve K.

**Comment by masinter** [comment]
I added as separate commits the change from .DCOMs.
I also added an experimental feature of taking the scripts of things to try to be a 
BKSYSBUFOBJ (from the DEMO commit in Medley). Try it! (MAKE-TEDIT-TEST AVTEST1)

**Comment by masinter** [comment]
> 1. Should the distribution of Medley now include the New Interlisp Readtable as default? 

The change of the INTERLISP readtable compared to OLD-INTERLISP-T and OLD-INTERLISP-FILE happened quite a long time ago (in the 90s at the latest).  The OLD-INTERLISP readtables don't have single-quote `'X` as an alternative to `(QUOTE X)` and don't treat : as a package delimiter.

The "new INTERLISP readtable" isn't new.

> 2. Did you make a change to the LOOPS Source code, so that I should download a new version?

The proposal in this PR (#17) does not include any changes to the LOOPS source code, but has some changes to the LOOPS/test folder in the Loops repository. My suggestion is you download, try, review and then approve this PR for merging.

 > 3.We need to com up with a mechanism for alerting users about such changes as they occur. I am sure that every release of Medley and, eventually, of LOOPS and other code, that changes will be made and they need to be posted somewhere for people to read. We should not require them, I don't think, to go to GitHub to find out what is changing. Steve K.

This function was the purpose of the "Release notes" to be a summary of things that have changed.

The Medley Release Notes were in the middle of being updated from Medley 2 to Medley 3.5.
Yes, we need more better introductory text.

That's a Documentation Issue.

**Comment by skaisler1** [comment]
Larry:
 
It seems then that the Loops example in the LRM may ave been written before the readtable change.Would probably need to go through PARC memos, etc to determine when. Thus, it seems to be a historical issue, but not one to alert readers, although in addition to Release Notes, we might need to have a Historical notes that captures the readtable change to inforom users who might have pre-199x (say) Lisp or LOOPS code.
 
I have downloaded and used your solutions. Many thanks and am includiing them in Medley LOOPS:Basic System.
 
I am not sure if I have the ability to approve PRs.
 
Steve K.

**Comment by masinter** [comment]
https://interlisp.org/pub-pdfs/all-medley.pdf#page=1515 Page 1515 explains.

**Pull request merged**
