### PR TITLE
Update Loops library GAUGE* DFASL files

### PR DESCRIPTION
**Pull request by nbriggs**
Existing DFASL files in loops/library were compiled with an old compiler that
is not compatible with Medley.  For now, only the GAUGE* DFASLs are being
replaced with new versions compiled from library-src, other files will (may)
be addressed in the future.

### CODE REVIEW

**Comment by nbriggs** [comment]
The process to recompile was

1. make a fresh loops sysout
2. set LOOPSLIBRARYDIRECTORY to ...>library-src> rather than ...>library>
3. (FILESLOAD (FROM VALUEOF LOOPSLIBRARYDIRECTORY) GAUGELOADER)
4. (LOADGAUGES NIL T)
5. note that everything loaded OK... if so:
6. for each file in GAUGEFILES, plus GAUGELOADER, do (CL:COMPILE-FILE file)
7. then move the new GAUGE*.DFASL to library
8. Check:  start a fresh loops sysout, (FILESLOAD GAUGELOADER) (LOADGAUGES)

**Review by rmkaplan — COMMENTED** [review]
I don't have a looops sysout, but I was able to LOADLOOPS.DFASL, then LOADLOOPS, then GAUGELOADER, then LOADGAUGES.

There was a glitch, however, in that the LOOPSDIRECTORY variable is only set to system/ so I had to figure out where to explicitly connect in order to find the guages.   Should more directories be pushed on LISPUSERSDIRECTORIES are DIRECTORIES, so that ordinary FILESLOAD will find these things?

**Comment by nbriggs** [comment]
I think the loaders are doing/supposed to be doing ... (FROM VALUEOF LOOPSLIBRARYDIRECTORY) ... (or LOOPSDIRECTORY, or LOOPSUSERSDIRECTORY).  There's a Truckin loader, too, that starts from a basic loops sysout and does all the right stuff.

Meanwhile, I'm continuing to get burned by the code doing (LOADCOMP FOO) when FOO is already compiled and loaded in the sysout... and CL:COMPILE-FILE fails because LOADCOMP says it can't find the file (in the place it's looking, which is probably the wrong place)

**Comment by nbriggs** [comment]
p.s., if your LOOPSDIRECTORY is set to system, then it should have also automatically figured out the right settings for LOOPSLIBRARYDIRECTORY and so on.   If you (LOADLOOPS "{dsk}<tmp>") it will make a LOOPS.SYSOUT in /tmp ...

**Comment by rmkaplan** [comment]
Yes, LOOPSLIBRARYDIRECTORY seems to be set, and if I do (FILESLOAD (FROM VALUEOF LOOPSLIBRARYDIRECTORY) GAUGELOADER) it finds the file.

What doesn’t seem to work is the other little abbreviations in DOFILESLOAD.  I would have thought that I could have said just
(FILESLOAD (FROM LOOPSLIBRARY) GAUGELOADER)
 or
(FILESLOAD (FROM LOOPSLIBRARYDIRECTORY) GAUGELOADER)

But for those it doesn’t find the file.  Maybe my misunderstanding of the heuristics in DOFILESLOAD.

Still it might be helpful to put the loops directories on the default search paths, either DIRECTORIES or LISPUSERSDIRECTORIES, just to be helpful.

I agree that loops itself is set up and loading, I’ll approve the pr.

**Review by rmkaplan — APPROVED** [review]
loading variables do seem to be set up as intended

**Comment by nbriggs** [comment]
> What doesn’t seem to work is the other little abbreviations in DOFILESLOAD.  I would have thought that I could have said just
(FILESLOAD (FROM LOOPSLIBRARY) GAUGELOADER)
 or
(FILESLOAD (FROM LOOPSLIBRARYDIRECTORY) GAUGELOADER)
But for those it doesn’t find the file.  Maybe my misunderstanding of the heuristics in DOFILESLOAD.

I had to go and look this up -- `(FROM FOO)` requires that `FOODIRECTORIES` (plural) be bound.  LOOPS uses the singular for its directory variables so requires the full `(FROM VALUEOF LOOPSLIBRARYDIRECTORY)` syntax.

**Comment by rmkaplan** [comment]
Ahh, I missed that.  I think DOFILESLOAD should allow both forms, I’ll add it to my list.

**Pull request merged**
